### ISSUE TITLE
Getting Monotheist when I REALLY shouldn't.

### ISSUE THREAD

**Issue by Elvenoob** [conormccauley1999/DichotomyTests#10]
I am a pagan and a polytheist, so it's kind of frustrating to answer "Strongly Disagree" on the question "Does an omnipotent, omnipresent etc. god exist", but still get the "Monotheist" badge thing at the end?

Like, yes, a few of the questions that're supposed to be more general to religion are worded a bit weirdly if you try to answer them as a non-christian religious person, but "monotheism" being the only religion related icon at the bottom is, um, much worse. 

I'd reccomend two things; That the question I mention above, whether or not, essentially the abrahamic god exists, should have a clause which completely rules out monotheism if the person hits disagree, and then if they're answering in a religious/spiritual manner from there, the later question of "does a god need to exist for us to be content" can be reworded a little to have "a god, or group of gods", and then someone who disagrees with the Abrahamic omni-whatever idea of god but answers yes to this question would instead get "Polytheist" (The celtic trinity knot would work well for a simple symbol there) and someone who answers no to both doesn't get a badge because that's sort of redundant since they'd still have a super-high spiritualist score, but with no deity belief on top of that.

**Comment by conormccauley1999** [comment]
The _"Monotheist"_ marker is given to users who get 60% or above in both spiritualism and moralism - individual questions don't have much of an effect on the result.

Perhaps we could simply change the name of the marker to _"Theist"_ and the icon to something more appropriate. There doesn't seem to be a reason to distinguish between polytheism and monotheism on this test as both share the spiritualism and moralism traits.

**Comment by conormccauley1999** [comment]
See commit 73b9e19 for changes.

**Comment by Elvenoob** [comment]
Eeeh, I think the relevant difference is a tendency of monotheism to claim it is the sole true religion and push around anyone who doesn't convert, whereas polytheists are generally a lot more chill with people of other religions (Except monotheists on account of the above tendancy.) Like, it's not so much purely focused on the stats, but on the wider philosophical differences those different systems have.

But yeah, if they both end up sharing the same marker the icon definitely needs a change because the cross just implies you're talking about monotheism again... 

Although the two belief systems are so different I don't know what icon could function for both of them.
