### ISSUE TITLE
The results page should not display number outside of 0-100%

### ISSUE THREAD

**Issue by Naereen** [conormccauley1999/DichotomyTests#3]
See this hand crafted example: http://www.dichotomytests.com/results.html?id=0&m=1244&e=1424&i=1244&h=2144&n=1442&r=1555&s=14451
![bad result](https://user-images.githubusercontent.com/11994719/49401993-f67ea100-f748-11e8-9b6d-4478b45970a3.png)

I can write a pull request to fix the javascript code, but you know your code better so it'll probably be (way) faster for you.

**Comment by Naereen** [comment]
Oh and by the way; GREAT test and :+1: :clap: good job on the UI !!!

**Comment by conormccauley1999** [comment]
Thanks for the support! Issue fixed also.

**Comment by Naereen** [comment]
Awesome! Thanks!
