### ISSUE TITLE
Reasoning behind the tests

### ISSUE THREAD

**Issue by vinisalazar** [conormccauley1999/DichotomyTests#4]
Hi,

do you have any source for the reasoning behind the test and the scores? Were the questions taken from anywhere, do they have any psychological or scientific basis behind them or did you come up with everything by yourself without any references (I would doubt that).

Nice work, btw. The test and results were quite interesting.

**Comment by conormccauley1999** [comment]
> do you have any source for the reasoning behind the test and the scores

The scales that each question has an effect on, as well as the size of that effect, were chosen based on our (limited) knowledge of the subject.

> do they have any psychological or scientific basis behind them

As far as I'm aware, the questions have no psychological or scientific basis.

> did you come up with everything by yourself without any references

We came up with many of the questions by ourselves. However, the rest were developed with the help of various sources: Wikipedia, books, quotes from philosophers, etc.

> Nice work, btw

Thank you!

**Comment by vinisalazar** [comment]
Thanks.

If you included your references, it would be very much appreciated.
