### ISSUE TITLE
is there a page with the possible result types?

### ISSUE THREAD

**Issue by beppe9000** [conormccauley1999/DichotomyTests#5]
likes hobbes and the rest

**Comment by conormccauley1999** [comment]
This feature will probably be added soon.

**Comment by beppe9000** [comment]
thanks! btw does this repository contain everything to run the webapp locally ?

**Comment by conormccauley1999** [comment]
The images are hosted separately. The URLs to each of the images are in the `tests.js` file. They are publicly available so you should be able to run the website locally.

**Comment by beppe9000** [comment]
oh didn't notice that. thanks for this project
