### ISSUE TITLE
Redirected to scam website

### ISSUE THREAD

**Issue by sman591** [conormccauley1999/DichotomyTests#6]
Clicking any link off of the homepage redirects to a different website. Many of them on mobile are ones promoting fake VPN or virus software for my phone

**Comment by conormccauley1999** [comment]
These are ads. They can be easily closed on mobile by closing the new tab, or if a prompt has appeared pressing the phone's back button.

**Comment by sman591** [comment]
Not sure about opening it normally, but I’m completely redirected to some scam website as soon as I click “Start the test”. Clicking the back button sends me to more ads.

**Comment by sman591** [comment]
Two ads I was directed to:

![a70c200a-4c17-4197-a7d3-8c778dc91533](https://user-images.githubusercontent.com/1441807/49592952-461ac380-f927-11e8-88ce-6621ffab8169.png)
![10171905-a350-48ac-bad2-762d2e6fef4d](https://user-images.githubusercontent.com/1441807/49592954-461ac380-f927-11e8-9f9f-80bb3d1b654f.png)

**Comment by conormccauley1999** [comment]
Did you try tapping the 'x' in the top-left corner? What happens if you do that?

**Comment by conormccauley1999** [comment]
I'm not sure what I can do to prevent this without disabling ads entirely. I'll look into it nonetheless.
