### ISSUE TITLE
Add descriptions and/or links to more information for the dichotomy button on results page

### ISSUE THREAD

**Issue by SouthernWolf95** [conormccauley1999/DichotomyTests#7]
It might be helpful if users, when hovering over the little button image of their dichotomy on the results page, see either a sentence or two of information about that dichotomy. It might also prove helpful to add a link to something like Wikipedia for that specific dichotomy as well. That way, users will have easier access to information about what their results show them as relating to.

**Comment by conormccauley1999** [comment]
There's a section at the bottom of the results page that shows some of this information already. It could be a good idea to add Wikipedia links to this section - as you suggested. I'll have a look. Thanks!

**Comment by conormccauley1999** [comment]
Yes, I understand now. This feature would certainly be worth adding - I'll look into it. Thanks!

**Comment by conormccauley1999** [comment]
Done. It only took 14 months.
