### ISSUE TITLE
Co-reference to other repos

### ISSUE THREAD

**Issue by DonaldTsang** [conormccauley1999/DichotomyTests#9]
Is it possible to integrate some of these elements into the test?
also this issue can be used to find more references
- https://github.com/RadicaliseesSurInternet/politiscales
- https://github.com/9Axes/9axes.github.io
- https://github.com/8values/8values.github.io
- https://github.com/LeftValues/leftvalues.github.io

**Comment by conormccauley1999** [comment]
Working on a politics test at the moment so some elements from those tests will probably be integrated.

**Comment by conormccauley1999** [comment]
Closing this issue as we've implemented a political philosophy test.

**Comment by DonaldTsang** [comment]
Thanks for making the test. Might be good to also release a note on comparisons between tests.
In other news take a look at https://rightvaluestest.github.io/

**Comment by DonaldTsang** [comment]
@conormccauley1999 please take a look at these ones as well
- https://altvalues.github.io/
- https://rightvaluestest.github.io/
- https://sapplyvalues.github.io/

For those who want to use triangles https://sixtriangles.github.io/
